# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shibkit-meta_meta}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Pete Birkinshaw}]
  s.date = %q{2011-08-14}
  s.description = %q{Library to download and parse SAML2 metadata}
  s.email = %q{pete@digitalidentitylabs.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Icon.png",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/shibkit/meta_meta.rb",
    "lib/shibkit/meta_meta/attribute.rb",
    "lib/shibkit/meta_meta/contact.rb",
    "lib/shibkit/meta_meta/config.rb",
    "lib/shibkit/meta_meta/data/default_metadata/example_federation_metadata.xml",
    "lib/shibkit/meta_meta/data/default_metadata/local_metadata.xml",
    "lib/shibkit/meta_meta/data/default_metadata/uncommon_federation_metadata.xml",
    "lib/shibkit/meta_meta/data/default_metadata_cache.yml",
    "lib/shibkit/meta_meta/data/dev_sources.yml",
    "lib/shibkit/meta_meta/data/real_sources.yml",
    "lib/shibkit/meta_meta/entity.rb",
    "lib/shibkit/meta_meta/federation.rb",
    "lib/shibkit/meta_meta/idp.rb",
    "lib/shibkit/meta_meta/logo.rb",
    "lib/shibkit/meta_meta/metadata_item.rb",
    "lib/shibkit/meta_meta/mixin/cached_downloads.rb",
    "lib/shibkit/meta_meta/mixin/xpath_chores.rb",
    "lib/shibkit/meta_meta/organisation.rb",
    "lib/shibkit/meta_meta/provider.rb",
    "lib/shibkit/meta_meta/provisioning/base.rb",
    "lib/shibkit/meta_meta/requested_attribute.rb",
    "lib/shibkit/meta_meta/service.rb",
    "lib/shibkit/meta_meta/source.rb",
    "lib/shibkit/meta_meta/sp.rb",
    "spec/config_spec.rb",
    "spec/contact_spec.rb",
    "spec/data/metadata_cache/README",
    "spec/entity_spec.rb",
    "spec/federation_spec.rb",
    "spec/meta_meta_spec.rb",
    "spec/metadata_spec.rb",
    "spec/organisation_spec.rb",
    "spec/source_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/support/fetch_federation_metadata.rb",
    "spec/support/supply_xml.rb"
  ]
  s.homepage = %q{http://github.com/binaryape/shibkit-meta_meta}
  s.licenses = [%q{Apache 2.0}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Parses SAML2 (Shibboleth) metadata}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<uuid>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client-components>, [">= 0"])
      s.add_runtime_dependency(%q<rack-cache>, [">= 0"])
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_runtime_dependency(%q<chunky_png>, [">= 0"])
      s.add_runtime_dependency(%q<dimensions>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<uuid>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<rest-client-components>, [">= 0"])
      s.add_dependency(%q<rack-cache>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<chunky_png>, [">= 0"])
      s.add_dependency(%q<dimensions>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<uuid>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<rest-client-components>, [">= 0"])
    s.add_dependency(%q<rack-cache>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<chunky_png>, [">= 0"])
    s.add_dependency(%q<dimensions>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

